#!/usr/bin/env bash
DOMAIN_SEPARATOR=0xafcac80a03e5119639bb0f77f7aa754ac902dbfa79074a8de9e50aea7ee83b6a
# permit type data
permit_TYPEHASH=$(seth keccak $(seth --from-ascii "Permit(address holder,address spender,uint256 nonce,uint256 expiry,bool allowed)"))

# permit data
HOLDER=0x78Df63f83d8CFfaeB2f5522102113a4Cb44bD857
SPENDER=0xc351B89C286288B9201835f78dbbccaDA357671e
NONCE=0
ALLOWED=1
DEADLINE=604414800

MESSAGE=0x1901\
$(echo $DOMAIN_SEPARATOR\
$(seth keccak \
$permit_TYPEHASH\
$(echo $(seth --to-uint256 $HOLDER)\
$(seth --to-uint256 $SPENDER)\
$(seth --to-uint256 $NONCE)\
$(seth --to-uint256 $DEADLINE)\
$(seth --to-uint256 $ALLOWED)\
      | sed 's/0x//g')) \
      | sed 's/0x//g')
SIG=$(ETH_FROM=$HOLDER ethsign msg --passphrase-file /dev/null --no-prefix --data $MESSAGE)

printf '{"permit": {"holder":"%s","spender":"%s","nonce":"%s", "expiry": "%s", "allowed": "%s", "v": "%s", "r": "%s", "s": "%s"}}\n' "$HOLDER" "$SPENDER" "$NONCE" "$DEADLINE" "$ALLOWED" $((0x$(echo "$SIG" | cut -c 131-132))) $(echo "$SIG" | cut -c 1-66) "0x"$(echo "$SIG" | cut -c 67-130)
